# Generated by Django 4.2 on 2024-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='ادرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='قعال / غیر فعال')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': ' دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقاله ها',
                'ordering': ['position'],
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='is_active',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='عکس مقاله'),
        ),
    ]
