# Generated by Django 4.2 on 2024-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article.category', verbose_name='دسته بندی مقاله'),
        ),
    ]
