# Generated by Django 4.2 on 2024-01-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': ' مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
    ]
