# Generated by Django 4.2 on 2024-01-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='ادرس مقاله')),
                ('description', models.TextField(verbose_name='توضیح مقاله')),
                ('image', models.ImageField(upload_to='articles')),
                ('is_active', models.BooleanField(default=True, verbose_name='قعال / غیر فعال')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقاله',
            },
        ),
    ]
