# Generated by Django 4.2 on 2024-01-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': ' مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
    ]
